services:

  backend:
    image: geek120804/image-back:latest
    build:
      context: ./Backend/
      dockerfile: dockerfile
    ports:
      - 8080:8000
    environment:
      - DJANGO_SETTINGS_MODULE=odc.settings
      - POSTGRES_HOST=database
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: odc
      POSTGRES_PASSWORD: odc123
      POSTGRES_DB: odcdb
    volumes:
      - pgdata:/var/lib/postgresql/database

  db-migrations:
    image: backend
    command: python manage.py migrate
    depends_on:
      - database
    profiles:
      - tools

  frontend:
    image: geek120804/image-front:latest
    build:
      context: ./Frontend
      dockerfile: dockerfile
    ports:
      - 5173:5173
    depends_on:
      - backend

volumes:
  pgdata:
    driver: local
