services:
  backend:
    image: fatimadiao20/image-back:latest
    ports:
      - 8000:8080
    environment:
      - DJANGO_SETTINGS_MODULE=odc.settings
      - POSTGRES_HOST=database
      - POSTGRES_DB=odcdb
      - POSTGRES_USER=odc
      - POSTGRES_PASSWORD=odc123
      - DATABASE_URL=postgres://odc:odc123@database:5432/odcdb
    command: python odc/manage.py runserver 0.0.0.0:8080
    depends_on:
      - database

  frontend:
    image: fatimadiao20/image-front:latest
    ports:
      - 5174:5173
    depends_on:
      - backend

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: odc
      POSTGRES_PASSWORD: odc123
      POSTGRES_DB: odcdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  db-migrations:
    image: fatimadiao20/image-back:latest
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        while ! pg_isready -h database -p 5432; do
          sleep 1
        done &&
        echo 'Database is ready! Applying migrations...' &&
        python odc/manage.py migrate
      "
    environment:
      - DJANGO_SETTINGS_MODULE=odc.settings
      - POSTGRES_HOST=database
      - POSTGRES_DB=odcdb
      - POSTGRES_USER=odc
      - POSTGRES_PASSWORD=odc123
      - DATABASE_URL=postgres://odc:odc123@database:5432/odcdb
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
